language: android

services:
- docker

before_script:
- openssl aes-256-cbc -K $encrypted_8d441ecbf331_key -iv $encrypted_8d441ecbf331_iv -in ./deploy/secret.tar.enc -out ./deploy/secret.tar -d
- cd ./deploy && tar xvf secret.tar && cd ../

script:
- docker build -t secretbookimage .
- echo $TRAVIS_BUILD_NUMBER
- docker run --env TRAVIS_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER --env TRAVIS_COMMIT_MESSAGE=$TRAVIS_COMMIT_MESSAGE secretbookimage env
- docker run --env TRAVIS_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER --env TRAVIS_COMMIT_MESSAGE=$TRAVIS_COMMIT_MESSAGE secretbookimage
