language: default

services:
- docker

before_script:
- openssl aes-256-cbc -K $encrypted_8d441ecbf331_key -iv $encrypted_8d441ecbf331_iv -in ./deploy/secret.tar.enc -out ./deploy/secret.tar -d
- cd ./deploy && tar xvf secret.tar && cd ../

script:
- docker build -t secretbookimage .
- docker run --env TRAVIS_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER --env TRAVIS_COMMIT_MESSAGE="$TRAVIS_COMMIT_MESSAGE" -v $TRAVIS_BUILD_DIR/dockerOut:/dockerOut:rw secretbookimage
- ls $TRAVIS_BUILD_DIR/dockerOut

branches:
  only:
    - dev
    - deploy
