language: android

services:
- docker

before_script:
- openssl aes-256-cbc -K $encrypted_8d441ecbf331_key -iv $encrypted_8d441ecbf331_iv -in ./deploy/secret.tar.enc -out ./deploy/secret.tar -d
- cd ./deploy && tar xvf secret.tar

script:
- docker build -t secretbookimage .
- docker run -it --rm secretbookimage
